import React from 'react'

export const metadata = {
    title: "About Page",
    description: "Generated by create next app",
  };


const page = () => {
  return (
    <div>
      About Page
    </div>
  )
}

export default page
