import React from 'react'

export const metadata = {
    title: "Contact Page",
    description: "Generated by create next app",
  };


const Contact = () => {
  return (
    <div>
      This is contact page
    </div>
  )
}

export default Contact;
